version: '3'

services:
  frontend:
    container_name: frontend_container
    hostname: frontend
    build: ./frontend/prova-standalone
    ports:
      - 4300:4300
    networks:
      - model_net
    depends_on:
      - backend
    restart: on-failure

  backend:
    container_name: backend_container
    build: ./backend
    ports:
      - 5000:5000
    networks:
      - model_net
    environment:
      - FLASK_ENV=development
      - FLASK_APP=prova.py
    restart: on-failure

networks:
    model_net:
      driver: bridge
